### ISSUE TITLE
Support for UE 5.2?

### ISSUE THREAD

**Issue by rR31N** [LouisRaverdy/DiscordPluginUE#12]

**Comment by Letspatrick** [comment]
Plz Update

**Comment by JuKu** [comment]
Please update the plugin to version 5.2 . :)
I think it's very important for many developers here.

**Comment by LouisRaverdy** [comment]
Hi, unfortunately the 5.2 will not come. It will only be on the Unreal Engine Marketplace. There’s no change between the 5.1 ans 5.2 so you can easily update the plugin by yourself.
Have a good day ;)
