### ISSUE TITLE
custom link

### ISSUE THREAD

**Issue by flush286** [LouisRaverdy/DiscordPluginUE#13]
Hello, is there a way to custom button in the rich presence. Like fivem server with custom button name and link.
![Caeaapture](https://github.com/LouisRaverdy/DiscordRPC/assets/112771274/48b718b8-f12e-480b-b3c2-b354b3c0fcc1)

**Comment by LouisRaverdy** [comment]
Hi, unfortunately this feature isn’t implemented. The discord API don’t offer the opportunity to add a button below.
