### ISSUE TITLE
Can i make custom buttons that redirect to the url of my steam store?

### ISSUE THREAD

**Issue by ZigZagBoi1** [LouisRaverdy/DiscordPluginUE#14]
My name is in closed beta and i'd like to have people's status display the games name and banner but also have a button that lets players check out the steam store page with a click of a button, i've seen it down with things like stream labs.

**Comment by bud3699** [comment]
I'm going to assume not easily. Not without custom c++ I imagine. Take a look in the plugin and see. You might need to read the discord dev docs

**Comment by LouisRaverdy** [comment]
There is currenty no way in this Plugin/SDK.
