### ISSUE TITLE
RPC shows wrong app

### ISSUE THREAD

**Issue by RazrabGit** [LouisRaverdy/DiscordPluginUE#19]
I have a problem that the RPC does not show the correct application, although everything is correctly shown in my profile information. This problem is present only in a built project. In the editor, RPC is shown only in the profile. How to solve it?
![image](https://github.com/LouisRaverdy/DiscordRPC/assets/73162496/f80b7a5b-3b9a-4eb0-8903-195318f35fd2)
![image](https://github.com/LouisRaverdy/DiscordRPC/assets/73162496/c0b6d4a0-355b-4722-b466-750cabcf1525)

**Comment by LouisRaverdy** [comment]
This is not a plugin problem. You must have an app running in the background.
