### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by MrSquid1yt** [LouisRaverdy/DiscordPluginUE#2]
Hi, I use your Plugin and very nice work but it doesn't work (for me) 
I followed the Tutorial and it seems right (see screenshot) 
Please help me.
![grafik](https://user-images.githubusercontent.com/59023075/192107467-28473779-e49d-428b-9d75-0f2eb7ebe189.png)

**Comment by LouisRaverdy** [comment]
Hello and thank you! I think your problem is that you haven't defined your game instance in the project settings. Project Settings -> Maps & Modes -> Game Instance Class)

**Comment by MrSquid1yt** [comment]
Hi, I had it already

**Comment by LouisRaverdy** [comment]
Did you execute the Set Rich Presence Info and the Send Presence ?

**Comment by MrSquid1yt** [comment]
Execute? How to execute it? In the "tutorial" is nothing

**Comment by LouisRaverdy** [comment]
Simply need to connect at the suite of the execution or anywhere in your code but to work you must connect it.

**Comment by MrSquid1yt** [comment]
So I can place it behind the init and connect the set Rich Presence with the back of the init, right?

**Comment by LouisRaverdy** [comment]
Exactly !

**Comment by MrSquid1yt** [comment]
Oh yea nice!! Please add it to the Tutorial.
It works 
![grafik](https://user-images.githubusercontent.com/59023075/192151742-63d2d6cc-652f-4e89-8049-66fd8e020bd8.png)

**Comment by LouisRaverdy** [comment]
Perfect ! I'll add it.
