### ISSUE TITLE
 Update request for Unrealv5.3

### ISSUE THREAD

**Issue by imthatdev** [LouisRaverdy/DiscordPluginUE#21]

**Comment by Letspatrick** [comment]
Jeep plz Update this plugin... plz

**Comment by Starbruhz** [comment]
I would also appreciate if the plugin was made compatible with Unreal engine 5.3.

Thank you in advance!

**Comment by CusYaBasic** [comment]
> I would also appreciate if the plugin was made compatible with Unreal engine 5.3.
> 
> Thank you in advance!

I have made a pull request to update too 5.3

**Comment by SyMoRk56** [comment]
**when?**

**Comment by MichaelGatesDev** [comment]
It's been 6 months since the original issue, 3 months since the last reply and there's an [active MR *with* approvals from January](https://github.com/LouisRaverdy/DiscordRPC/pull/24#pullrequestreview-1807876785)...
