### ISSUE TITLE
DiscordRpc Not showing Up in packaged build

### ISSUE THREAD

**Issue by Just-Random-Dev** [LouisRaverdy/DiscordPluginUE#22]
title

**Comment by CusYaBasic** [comment]
> title

It works as long as you don't use the timestamp features I've noticed.

**Comment by CusYaBasic** [comment]
> > title
> 
> It works as long as you don't use the timestamp features I've noticed.

this has been fixed in an update, jus hoping OP accepts merge request!

**Comment by Just-Random-Dev** [comment]
im using the latest version but im on 5.2 so i could be the source of problem

**Comment by CusYaBasic** [comment]
> im using the latest version but im on 5.2 so i could be the source of problem

I think it was just some type issues that was created by int and int64 with timestamps. i did send a merge request, just waiting for OP to accept updates. if not i made my own fork for 5.2 and 5.3, you can check them out here:

5.3:  
https://github.com/CusYaBasic/DiscordRPC/tree/Unreal-Engine-5.3  

and 5.2 here:  
https://github.com/CusYaBasic/DiscordRPC/tree/Unreal-Engine-5.2

**Comment by Just-Random-Dev** [comment]
Thanks
