### ISSUE TITLE
Plugin fails to load for the packaged executable

### ISSUE THREAD

**Issue by gregorhcs** [LouisRaverdy/DiscordPluginUE#3]
### Setup
I've included the plugin in its 1.0.0 release version to my Unreal 5.0.3 project.

It is placed in the `Plugins` directory of my project as described in the instructions,
and was activated in the plugin settings.

### Issue
When I package the game and start the executable, the program starts and immediately shows the following error message:
![grafik](https://user-images.githubusercontent.com/42077794/193707375-0f19d7fb-5f57-4cb6-9c1c-32dc20b816fa.png)

### Additional Information
The plugin works just fine in the editor!

**Comment by LouisRaverdy** [comment]
Hi, thanks you for your report ! I'll investigate on it, I'll come back to you when I have more information the issue.

**Comment by LouisRaverdy** [comment]
Okay, I'm sorry for the late reply. The only thing you can do for fix the issue is add a C++ class or simply create a C++ project. Once done, the problem should be solved.
