### ISSUE TITLE
How the hell do you get the set node. 

### ISSUE THREAD

**Issue by DeadSyntaxdev** [LouisRaverdy/DiscordPluginUE#5]
I'm having trouble getting the "SET" node for my game instance. What is it called/How do I get it?

**Comment by LouisRaverdy** [comment]
The node is called "Set Rich presence info" but you should uncheck the context sensitive to get it. Tell me if you have any other problem.

**Comment by DeadSyntaxdev** [comment]
Wow that was fast thank you for responding fast. I'll try it now.

**Comment by DeadSyntaxdev** [comment]
Ok so I meant this node 
![image](https://user-images.githubusercontent.com/81271362/197215302-8dc32591-ac41-4b56-84a4-3b3e849e008d.png)

**Comment by LouisRaverdy** [comment]
Oh you mean the second node of this screenshoot ? It's just a "Construct Object from class".

**Comment by DeadSyntaxdev** [comment]
No I meant the set node-

**Comment by LouisRaverdy** [comment]
It's just a set to a var you need to create. You absolutely need it for using other nodes.

**Comment by DeadSyntaxdev** [comment]
How do I go about creating it?

**Comment by LouisRaverdy** [comment]
Just like create a new variable but set the type to "Discord" instead of bool or anything else.
