### ISSUE TITLE
Will you update the plugin to 5.1?

### ISSUE THREAD

**Issue by whostea** [LouisRaverdy/DiscordPluginUE#6]

**Comment by So2K** [comment]
pls

**Comment by LouisRaverdy** [comment]
The plugins doesn't work on 5.1 ?

**Comment by BlueBerrySans365** [comment]
Nope, UE5.1 can't even rebuild it

**Comment by LouisRaverdy** [comment]
Hey, I just went to push a new version to UE5.1. I hope it works for you.

**Comment by BlueBerrySans365** [comment]
Oh, thanks, I'll check asap)

**Comment by Underwater008** [comment]
The 5.1 version still does not work. Cannot rebuild and compile after update from 5.0 to 5.1

**Comment by LouisRaverdy** [comment]
Did you download the binaries plugin ?

**Comment by LouisRaverdy** [comment]
You're not supposed to rebuild it

**Comment by Underwater008** [comment]
> Did you download the binaries plugin ?

I had the 5.0 version, and it works in the editor but not after package. I deleted the 5.0 version and added the 5.1 version, but now I cannot open the project anymore, got compiler error. Should I not rebuild when opening the project?

**Comment by LouisRaverdy** [comment]
No, you just need to re download the new version of the plugin in the release page just [here](https://github.com/LouisRaverdy/DiscordRPC/releases)

**Comment by Underwater008** [comment]
I downloaded and extracted, replaced the old 5.0 version in the /plugin folder, and packaged successfully but cannot open the .exe file after. shows this message: https://ibb.co/hMjZsRf

**Comment by LouisRaverdy** [comment]
Can you send me a screen inside your .uproject ?

**Comment by Underwater008** [comment]
```
{
	"FileVersion": 3,
	"EngineAssociation": "5.1",
	"Category": "",
	"Description": "",
	"Plugins": [
		{
			"Name": "ModelingToolsEditorMode",
			"Enabled": true,
			"TargetAllowList": [
				"Editor"
			]
		},
		{
			"Name": "DiscordRpc",
			"Enabled": false
		}
	]
}
```

**Comment by Underwater008** [comment]
When its enabled:
```
{
	"FileVersion": 3,
	"EngineAssociation": "5.1",
	"Category": "",
	"Description": "",
	"Plugins": [
		{
			"Name": "ModelingToolsEditorMode",
			"Enabled": true,
			"TargetAllowList": [
				"Editor"
			]
		},
		{
			"Name": "DiscordRpc",
			"Enabled": true
		}
	]
}
```

**Comment by LouisRaverdy** [comment]
Okay tonight I'il try to repackage the plugin I know probably where is the issue

**Comment by LouisRaverdy** [comment]
Ok now it should works !

**Comment by Underwater008** [comment]
Still can not open the packaged build and shows me the same message: [https://ibb.co/hMjZsRf](url)

**Comment by LouisRaverdy** [comment]
Have you a c++ project ?

**Comment by BlueBerrySans365** [comment]
Blueprint project - works!
Thanks)

**Comment by LouisRaverdy** [comment]
Nice !
