### ISSUE TITLE
Does this plugin work on Android?

### ISSUE THREAD

**Issue by Shieldowskyy** [LouisRaverdy/DiscordPluginUE#7]
I'm creating a mobile game and I want it to have Discord RPC functionality. Will this plugin work on mobile devices?

**Comment by Shieldowskyy** [comment]
I managed to add the plugin correctly and it works in the editor but when packing to Android I get this error:

`UATHelper: Packaging (Android (ETC2)):     [1/16] PCH.DiscordRpc.h [arm64]
UATHelper: Packaging (Android (ETC2)):     [2/16] PCH.NativizedAssets.h [arm64]
UATHelper: Packaging (Android (ETC2)):     [3/16] Module.NativizedAssets.gen.1_of_2.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [4/16] Module.NativizedAssets.gen.2_of_2.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [5/16] SharedPCH.Engine.ShadowErrors.h [arm64]
UATHelper: Packaging (Android (ETC2)):     [6/16] Module.DiscordRpc.gen.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [7/16] DSHrunnerGame.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [8/16] Module.DiscordRpc.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [9/16] Module.Sentry.gen.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [10/16] Module.Sentry.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [11/16] Module.GameJoltAPI.gen.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [12/16] Module.GameJoltAPI.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [13/16] Module.NativizedAssets.1_of_2.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [14/16] Module.NativizedAssets.2_of_2.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [15/16] DSHrunnerGame-Android-Shipping-arm64.so
UATHelper: Packaging (Android (ETC2)):     ld.lld: error: undefined symbol: Discord_Initialize
UATHelper: Packaging (Android (ETC2)):     >>> referenced by DiscordRpcBlueprint.cpp:105 (C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Source/DiscordRpc/Private\DiscordRpcBlueprint.cpp:105)
UATHelper: Packaging (Android (ETC2)):     >>>               C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Intermediate/Build/Android/UE4/Shipping/DiscordRpc/Module.DiscordRpc.cppa8.o:(UDiscordRpc::Initialize(FString const&, bool, FString const&))
UATHelper: Packaging (Android (ETC2)):   
UATHelper: Packaging (Android (ETC2)):     ld.lld: error: undefined symbol: Discord_Shutdown
UATHelper: Packaging (Android (ETC2)):     >>> referenced by DiscordRpcBlueprint.cpp:111 (C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Source/DiscordRpc/Private\DiscordRpcBlueprint.cpp:111)
UATHelper: Packaging (Android (ETC2)):     >>>               C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Intermediate/Build/Android/UE4/Shipping/DiscordRpc/Module.DiscordRpc.cppa8.o:(UDiscordRpc::Shutdown())
UATHelper: Packaging (Android (ETC2)):   
UATHelper: Packaging (Android (ETC2)):     ld.lld: error: undefined symbol: Discord_RunCallbacks
UATHelper: Packaging (Android (ETC2)):     >>> referenced by DiscordRpcBlueprint.cpp:117 (C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Source/DiscordRpc/Private\DiscordRpcBlueprint.cpp:117)
UATHelper: Packaging (Android (ETC2)):     >>>               C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Intermediate/Build/Android/UE4/Shipping/DiscordRpc/Module.DiscordRpc.cppa8.o:(UDiscordRpc::RunCallbacks())
UATHelper: Packaging (Android (ETC2)):   
UATHelper: Packaging (Android (ETC2)):     ld.lld: error: undefined symbol: Discord_UpdatePresence
UATHelper: Packaging (Android (ETC2)):     >>> referenced by DiscordRpcBlueprint.cpp:159 (C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Source/DiscordRpc/Private\DiscordRpcBlueprint.cpp:159)
UATHelper: Packaging (Android (ETC2)):     >>>               C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Intermediate/Build/Android/UE4/Shipping/DiscordRpc/Module.DiscordRpc.cppa8.o:(UDiscordRpc::UpdatePresence())
UATHelper: Packaging (Android (ETC2)):   
UATHelper: Packaging (Android (ETC2)):     ld.lld: error: undefined symbol: Discord_ClearPresence
UATHelper: Packaging (Android (ETC2)):     >>> referenced by DiscordRpcBlueprint.cpp:164 (C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Source/DiscordRpc/Private\DiscordRpcBlueprint.cpp:164)
UATHelper: Packaging (Android (ETC2)):     >>>               C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Intermediate/Build/Android/UE4/Shipping/DiscordRpc/Module.DiscordRpc.cppa8.o:(UDiscordRpc::ClearPresence())
UATHelper: Packaging (Android (ETC2)):   
UATHelper: Packaging (Android (ETC2)):     ld.lld: error: undefined symbol: Discord_Respond
UATHelper: Packaging (Android (ETC2)):     >>> referenced by DiscordRpcBlueprint.cpp:171 (C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Source/DiscordRpc/Private\DiscordRpcBlueprint.cpp:171)
UATHelper: Packaging (Android (ETC2)):     >>>               C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Intermediate/Build/Android/UE4/Shipping/DiscordRpc/Module.DiscordRpc.cppa8.o:(UDiscordRpc::Respond(FString const&, int))
UATHelper: Packaging (Android (ETC2)):     >>> referenced by DiscordRpcBlueprint.cpp:171 (C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Source/DiscordRpc/Private\DiscordRpcBlueprint.cpp:171)
UATHelper: Packaging (Android (ETC2)):     >>>               C:/Users/krzys/Documents/Unreal Projects/DSHrunnerGame/Plugins/DiscordRpc/Intermediate/Build/Android/UE4/Shipping/DiscordRpc/Module.DiscordRpc.cppa8.o:(UDiscordRpc::Respond(FString const&, int))
UATHelper: Packaging (Android (ETC2)):     clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Packaging (Android (ETC2)): Took 58,766042s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Android (ETC2)): UnrealBuildTool failed. See log for more details. (C:\Users\krzys\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.27\UBT-DSHrunnerGame-Android-Shipping_2.txt)
UATHelper: Packaging (Android (ETC2)): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Android (ETC2)): BUILD FAILED
PackagingResults: Error: Unknown Error`

EDIT: Never mind, it was a Blueprint Nativization error. I will check if the game will run on android.

**Comment by Shieldowskyy** [comment]
The game crashes when launching on Android. Is there any way to make a plugin to work on mobile?

**Comment by LouisRaverdy** [comment]
Unfontally, the RPC can't work on iOS and Android due to the Discord app
