### ISSUE TITLE
Dont find a block

### ISSUE THREAD

**Issue by Partymann2000** [LouisRaverdy/DiscordPluginUE#8]
![image](https://user-images.githubusercontent.com/53320411/224787292-9519e66e-36b7-4d8e-a7b0-98a137c3044c.png)
Can you help me why i dont can find the clear peresence block

**Comment by LouisRaverdy** [comment]
Hi, you need to create node from your var 'Discord Ref'

**Comment by Partymann2000** [comment]
can you tell me how can i create a n ode im new on UE sry

**Comment by Partymann2000** [comment]
and a other question is this right?
![image](https://user-images.githubusercontent.com/53320411/224788684-e565327d-2e9d-4367-8ae4-41c04000122f.png)

**Comment by LouisRaverdy** [comment]
Create a get of this variable, and from this create a new node called clear presence

**Comment by Partymann2000** [comment]
> and a other question is this right? ![image](https://user-images.githubusercontent.com/53320411/224788684-e565327d-2e9d-4367-8ae4-41c04000122f.png)

okay can u tell me if this is the right i have selected

**Comment by LouisRaverdy** [comment]
yes

**Comment by Partymann2000** [comment]
Okay, my last probelm is i dont can see it on discord :/
![image](https://user-images.githubusercontent.com/53320411/224791141-cb846ab9-942f-4331-b8c8-11a0f74b4ddc.png)

**Comment by Partymann2000** [comment]
nd the error, thank you for your help! It would be cool if you would expand your documentation, it says it's coming soon :)
