### ISSUE TITLE
Export Problem

### ISSUE THREAD

**Issue by Partymann2000** [LouisRaverdy/DiscordPluginUE#9]
When I export my game and then start it, it says the plugin was not found although it works in the ue5 editor.

**Comment by LouisRaverdy** [comment]
Where you put the plugin ?

**Comment by Partymann2000** [comment]
![image](https://user-images.githubusercontent.com/53320411/226102277-e1ae879c-5db6-48a2-9682-31d7f422fd60.png)

**Comment by LouisRaverdy** [comment]
What version of unreal are you using ? And can you take a screenshoot of the error ?

**Comment by Partymann2000** [comment]
![image](https://user-images.githubusercontent.com/53320411/226111438-b1f0c8a0-4b07-4473-86e6-e91fd8c8b0f0.png)

UE5 1.1

**Comment by LouisRaverdy** [comment]
Please re download the plugin in the release, and make sure you .uproject is correctly configured.

**Comment by Partymann2000** [comment]
its dont work its the say error but i have a code

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

0x00007ff781769f16 UnrealGame.exe!FSlateRHIRenderer::DrawWindows_Private() []
0x00007ff781c348e7 UnrealGame.exe!FMoviePlayerWidgetRenderer::DrawWindow() []
0x00007ff781c3e2b2 UnrealGame.exe!FSlateLoadingSynchronizationMechanism::SlateThreadRunMainLoop() []
0x00007ff781c3ba10 UnrealGame.exe!FSlateLoadingThreadTask::Run() []
0x00007ff77dd23a02 UnrealGame.exe!FRunnableThreadWin::Run() []
0x00007ff77dd1b800 UnrealGame.exe!FRunnableThreadWin::GuardedRun() []
0x00007ff810b926bd KERNEL32.DLL!UnknownFunction []
0x00007ff81186a9f8 ntdll.dll!UnknownFunction []

Crash in runnable thread SlateLoadingThread1

**Comment by LouisRaverdy** [comment]
It's a problem of you project, pls try in anoter project? Aditionally I update a new version of the plugin for UE5.1.1.

**Comment by Partymann2000** [comment]
its also work not in other projekt after exports

**Comment by LouisRaverdy** [comment]
Do you redowload the new version on the github ?

**Comment by Partymann2000** [comment]
Nope dosnt work and the last upload was last year

**Comment by LouisRaverdy** [comment]
My bad ! The release was in private. It should be fixed

**Comment by Partymann2000** [comment]
it still doesn't work i just don't understand why

**Comment by LouisRaverdy** [comment]
i tested again and it works. Are you using the plugin with a c++ project ?

**Comment by Partymann2000** [comment]
I don't know I use blueprints

**Comment by Partymann2000** [comment]
i have find a line
PackagingResults: Error: System.ArgumentException: An item with the same key has already been added. Key: DiscordRpc

**Comment by Partymann2000** [comment]
![image](https://user-images.githubusercontent.com/53320411/227787669-5c432f66-e07b-45b6-a3a3-07b520e6f80a.png)

**Comment by LouisRaverdy** [comment]
The code seems be correct. Just try to create a c++ project and try again.
